function(netkit_apply_sanitizer TARGET NAME FLAG)
    if(${NAME})
        if(WIN32 AND CMAKE_C_COMPILER_ID STREQUAL "MSVC")
            target_compile_options(${TARGET} PRIVATE "/fsanitize=${FLAG}")
            target_link_options(${TARGET} PRIVATE "/fsanitize=${FLAG}")
        endif()
    endif()
endfunction()

function(netkit_add_test test_name)
    add_executable(test-${test_name} "test-${test_name}.c")
    target_link_libraries(test-${test_name} PRIVATE netkit)
    target_include_directories(test-${test_name} PRIVATE ${CMAKE_SOURCE_DIR}/src)
    add_test(NAME ${test_name} COMMAND test-${test_name})

    netkit_apply_sanitizer(test-${test_name} NETKIT_ENABLE_ASAN address)
    netkit_apply_sanitizer(test-${test_name} NETKIT_ENABLE_TSAN thread)
    netkit_apply_sanitizer(test-${test_name} NETKIT_ENABLE_UBSAN undefined)

    if(NETKIT_ENABLE_COVERAGE AND UNIX)
        target_link_options(test-${test_name} PRIVATE --coverage)
    endif()
endfunction()
