function({project}_apply_sanitizer TARGET NAME FLAG)
    if(${NAME})
        if(WIN32 AND CMAKE_C_COMPILER_ID STREQUAL "MSVC")
            target_compile_options(${TARGET} PRIVATE "/fsanitize=${FLAG}")
            target_link_options(${TARGET} PRIVATE "/fsanitize=${FLAG}")
        elseif(UNIX)
            target_compile_options(${TARGET} PRIVATE "-fsanitize=${FLAG}" -fno-omit-frame-pointer)
            target_link_options(${TARGET} PRIVATE "-fsanitize=${FLAG}")
        endif()
    endif()
endfunction()

function({project}_add_test test_name)
    add_executable(test-${test_name} "test-${test_name}.c")
    target_link_libraries(test-${test_name} PRIVATE {project})
    add_test(NAME ${test_name} COMMAND test-${test_name})

    {project}_apply_sanitizer(test-${test_name} {PROJECT}_ENABLE_ASAN address)
    {project}_apply_sanitizer(test-${test_name} {PROJECT}_ENABLE_TSAN thread)
    {project}_apply_sanitizer(test-${test_name} {PROJECT}_ENABLE_UBSAN undefined)

    if({PROJECT}_ENABLE_COVERAGE AND UNIX)
        target_link_options(test-${test_name} PRIVATE --coverage)
    endif()
endfunction()
